// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWxHR__8nGRCm1MbpJ5sE-5w6L1shGp1Q',
    appId: '1:94596106795:web:f7cdeb24dfc4a4daa4786e',
    messagingSenderId: '94596106795',
    projectId: 'movie-98bcd',
    authDomain: 'movie-98bcd.firebaseapp.com',
    databaseURL: 'https://movie-98bcd-default-rtdb.firebaseio.com',
    storageBucket: 'movie-98bcd.firebasestorage.app',
    measurementId: 'G-JCV36MELYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xpq9zH60j0Q0i6qg9ebCagXYtZWpfCU',
    appId: '1:94596106795:android:2a29b0f214eb2da6a4786e',
    messagingSenderId: '94596106795',
    projectId: 'movie-98bcd',
    databaseURL: 'https://movie-98bcd-default-rtdb.firebaseio.com',
    storageBucket: 'movie-98bcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvToerkSYY0bGjnIzT8LRDOeSsM_4L8tE',
    appId: '1:94596106795:ios:2ac56f420a4018fda4786e',
    messagingSenderId: '94596106795',
    projectId: 'movie-98bcd',
    databaseURL: 'https://movie-98bcd-default-rtdb.firebaseio.com',
    storageBucket: 'movie-98bcd.firebasestorage.app',
    iosClientId: '94596106795-1q36e892vcns5qlt09bimtcos096sib2.apps.googleusercontent.com',
    iosBundleId: 'com.example.movei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvToerkSYY0bGjnIzT8LRDOeSsM_4L8tE',
    appId: '1:94596106795:ios:2ac56f420a4018fda4786e',
    messagingSenderId: '94596106795',
    projectId: 'movie-98bcd',
    databaseURL: 'https://movie-98bcd-default-rtdb.firebaseio.com',
    storageBucket: 'movie-98bcd.firebasestorage.app',
    iosClientId: '94596106795-1q36e892vcns5qlt09bimtcos096sib2.apps.googleusercontent.com',
    iosBundleId: 'com.example.movei',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWxHR__8nGRCm1MbpJ5sE-5w6L1shGp1Q',
    appId: '1:94596106795:web:e1a9d4b9502ae062a4786e',
    messagingSenderId: '94596106795',
    projectId: 'movie-98bcd',
    authDomain: 'movie-98bcd.firebaseapp.com',
    databaseURL: 'https://movie-98bcd-default-rtdb.firebaseio.com',
    storageBucket: 'movie-98bcd.firebasestorage.app',
    measurementId: 'G-L7JXK09X4E',
  );
}
